# Generated by Django 3.2.23 on 2023-11-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epa_number', models.CharField(max_length=25)),
                ('signal_word', models.CharField(choices=[('C', 'Caution'), ('D', 'Danger'), ('W', 'Warning')], max_length=2)),
                ('status', models.CharField(choices=[('I', 'Inactive'), ('T', 'Trial'), ('R', 'Retired'), ('I', 'Inactive')], default='A', max_length=1)),
            ],
        ),
    ]
