# Generated by Django 3.2.23 on 2023-11-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0002_auto_20231119_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuvant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epa_number', models.CharField(blank=True, max_length=25)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesticides.manufacturer')),
            ],
        ),
    ]
