# Generated by Django 3.2.23 on 2023-11-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0003_adjuvant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticide',
            name='status',
            field=models.CharField(choices=[('I', 'Inactive'), ('T', 'Trial'), ('R', 'Retired'), ('A', 'Active')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('concentration', models.CharField(choices=[('Percent', '%'), ('Gallon', '/gallon')], default='Percent', max_length=10)),
                ('adjuvant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesticides.adjuvant')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesticides.pesticide')),
            ],
        ),
        migrations.AddField(
            model_name='pesticide',
            name='formulas',
            field=models.ManyToManyField(through='pesticides.Formula', to='pesticides.Adjuvant'),
        ),
    ]
