# Generated by Django 3.2.23 on 2023-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0005_auto_20231120_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula',
            old_name='amount',
            new_name='adjuvant_amount',
        ),
        migrations.AddField(
            model_name='formula',
            name='adjuvant_concentration',
            field=models.CharField(choices=[('P', '%'), ('G', '/gallon')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='formula',
            name='pesticide_amount',
            field=models.DecimalField(decimal_places=3, max_digits='4', max_length=20, null=True),
        ),
    ]
