# Generated by Django 3.2.23 on 2023-11-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0009_applicator_park_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_size', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('targeted_species', models.CharField(max_length=200)),
                ('weather', models.CharField(max_length=200)),
                ('applicator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pesticides.applicator')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pesticides.formula')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pesticides.park')),
            ],
        ),
    ]
